version: '{build}'
os: Visual Studio 2015

configuration:
- Debug

cache:
- vcpkg -> .appveyor.yml

environment:
  matrix:
  - STATIC: OFF
    PLATFORM: Win32
    GENERATOR: "Visual Studio 14 2015"
    BUILD_TYPE: Release
  - STATIC: ON
    PLATFORM: Win32
    GENERATOR: "Visual Studio 14 2015"
    BUILD_TYPE: Debug
  - STATIC: ON
    PLATFORM: x64
    GENERATOR: "Visual Studio 14 2015 Win64"
    BUILD_TYPE: Release
  - STATIC: OFF
    PLATFORM: x64
    GENERATOR: "Visual Studio 14 2015 Win64"
    BUILD_TYPE: Debug

configuration: %BUILD_TYPE%

init: []

install:
- if not exist vcpkg git clone https://github.com/Microsoft/vcpkg
- cd vcpkg
- if not exist downloads mkdir downloads
- if not exist downloads\AlwaysAllowDownloads type nul > downloads\AlwaysAllowDownloads
- powershell -exec bypass scripts\bootstrap.ps1
- vcpkg install cryptopp:x64-windows zlib:x64-windows expat:x64-windows cryptopp:x86-windows zlib:x86-windows expat:x86-windows
- vcpkg integrate install
- cd ..

before_build:
- cmake -H. -Bbuild -G%GENERATOR% -DSTATIC=%STATIC% -DSAMPLES=ON -DBENCHMARKS=ON -DCMAKE_TOOLCHAIN_FILE=vcpkg/scripts/buildsystems/vcpkg.cmake

build:
  project: build/tests/xlnt.test.sln
  parallel: true
  verbosity: minimal

test_script:
- cd build\tests\%BUILD_TYPE%
- set PATH=C:\projects\xlnt\vcpkg\installed\%PLATFORM%-windows\debug\bin;%PATH%
- xlnt.test.exe
