version: '{build}'
os: Previous Visual Studio 2015

configuration:
- Debug

environment:
  matrix:
  - STATIC: OFF
  - STATIC: ON

init: []
install: []
before_build:
- git submodule update --init --recursive
- mkdir build
- cd build
- cmake -G "Visual Studio 14 2015 Win64" -D STATIC=%STATIC% ..
- ls .

build:
  project: xlnt_all.sln
  parallel: true
  verbosity: minimal

test_script:
- cd bin
- xlnt.test.exe
