version: '{build}'
os: Visual Studio 2015

configuration:
- Debug

environment:
  matrix:
  - STATIC: OFF
  - STATIC: ON

init: []
install:
- git clone https://github.com/Microsoft/vcpkg
- cd vcpkg
- powershell -exec bypass scripts\bootstrap.ps1
- vcpkg install cryptopp zlib
- vcpkg integrate install
- cd ..

before_build:
- git submodule update --init
- cmake -H. -Bbuild -G"Visual Studio 14 2015 Win64" -DSTATIC=%STATIC% -DSAMPLES=ON -DBENCHMARKS=ON

build:
  project: build/tests/xlnt.test.sln
  parallel: true
  verbosity: minimal

test_script:
- cd build/bin
- xlnt.test.exe
