version: '{build}'
os: Previous Visual Studio 2015

configuration:
- Debug

environment:
  matrix:
  - SHARED: ON
    STATIC: OFF
  - SHARED: OFF
    STATIC: ON

init: []
install: []
before_build:
- git submodule update --init --recursive
- cmake -H. -Bbuild -G"Visual Studio 14 2015 Win64" -DSHARED=%SHARED% -DSTATIC=%STATIC% -DWITH_SAMPLES=ON

build:
  project: build\xlnt.sln
  parallel: true
  verbosity: minimal

test_script:
- cd build\bin
- xlnt.test.exe
