version: '{build}'
os: Visual Studio 2015

cache:
- vcpkg -> .appveyor.yml

platform:
  - x86
  - x64

configuration:
  - Debug
  - Release

environment:
  matrix:
  - STATIC: OFF
  - STATIC: ON

init: []

install:
- if not exist vcpkg git clone https://github.com/Microsoft/vcpkg
- cd vcpkg
- if not exist downloads mkdir downloads
- if not exist downloads\AlwaysAllowDownloads type nul > downloads\AlwaysAllowDownloads
- powershell -exec bypass scripts\bootstrap.ps1
- vcpkg install cryptopp:x64-windows zlib:x64-windows expat:x64-windows cryptopp:x86-windows zlib:x86-windows expat:x86-windows
- vcpkg integrate install
- cd ..

before_build:
- cmake -H. -Bbuild -DSTATIC=%STATIC% -DSAMPLES=ON -DBENCHMARKS=ON -DCMAKE_TOOLCHAIN_FILE=vcpkg/scripts/buildsystems/vcpkg.cmake

build:
  project: build/tests/xlnt.test.sln
  parallel: true
  verbosity: minimal

test_script:
- cd build\tests\${configuration}
- set PATH=C:\projects\xlnt\vcpkg\installed\${platform}-windows\debug\bin;%PATH%
- xlnt.test.exe
