version: '{build}'
os: Visual Studio 2015

configuration:
- Debug

cache:
- vcpkg -> .appveyor.yml

environment:
  matrix:
  - STATIC: OFF
  - STATIC: ON

init: []
install:
- if not exist vcpkg git clone https://github.com/Microsoft/vcpkg
- cd vcpkg
- if not exist downloads mkdir downloads
- if not exist downloads\AlwaysAllowDownloads type nul > downloads\AlwaysAllowDownloads
- powershell -exec bypass scripts\bootstrap.ps1
- vcpkg install cryptopp:x64-windows zlib:x64-windows expat:x64-windows
- vcpkg integrate install
- cd ..

before_build:
- cmake -H. -Bbuild -G"Visual Studio 14 2015 Win64" -DSTATIC=%STATIC% -DSAMPLES=ON -DBENCHMARKS=ON -DCMAKE_TOOLCHAIN_FILE=vcpkg/scripts/buildsystems/vcpkg.cmake

build:
  project: build/tests/xlnt.test.sln
  parallel: true
  verbosity: minimal

test_script:
- cd build\tests\Debug
- set PATH=C:\projects\xlnt\vcpkg\installed\x64-windows\debug\bin;%PATH%
- xlnt.test.exe
