version: '{build}'
os: Visual Studio 2015

configuration:
- Debug

environment:
  matrix:
  - STATIC: OFF
  - STATIC: ON

init: []
install:
- git clone https://github.com/Microsoft/vcpkg
- cd vcpkg
- git checkout 47b53b9015deaa2f569d788447254c8bc3de96a9
- mkdir downloads
- type nul > downloads\AlwaysAllowDownloads
- powershell -exec bypass scripts\bootstrap.ps1
- vcpkg install cryptopp zlib expat
- vcpkg integrate install
- cd ..

before_build:
- vcpkg\downloads\cmake-3.8.0-rc1-win32-x86\bin\cmake.exe -H. -Bbuild -G"Visual Studio 14 2015" -DSTATIC=%STATIC% -DSAMPLES=ON -DBENCHMARKS=ON -DCMAKE_TOOLCHAIN_FILE=vcpkg/scripts/buildsystems/vcpkg.cmake -DCMAKE_ROOT=vcpkg/downloads/cmake-3.8.0-rc1-win32-x86 -DCRYPTOPP_LIBRARY=vcpkg/installed/x86-windows/lib/cryptopp-static.lib

build:
  project: build/tests/xlnt.test.sln
  parallel: true
  verbosity: minimal

test_script:
- cd build/bin
- xlnt.test.exe
