# from: https://github.com/nlohmann/json/blob/master/.travis.yml

language: cpp

sudo: required
dist: trusty

notifications:
  email: false

matrix:
  include:
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: 
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
            - python-pip
      before_script:
        - pip install --user git+git://github.com/eddyxu/cpp-coveralls.git
      env: 
        - COMPILER=g++-4.9
        - COVERAGE=ON
        - STATIC=ON
        - SAMPLES=OFF

    - os: linux
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
            - valgrind
      env:
        - COMPILER=g++-5
        - COVERAGE=OFF
        - STATIC=OFF
        - SAMPLES=ON

script:
  - mkdir build
  - cd build
  - cmake -D STATIC=$STATIC -D SAMPLES=$STATIC -D COVERAGE=$COVERAGE -D CMAKE_CXX_COMPILER=$COMPILER -D CMAKE_BUILD_TYPE=Debug ..
  - cmake --build .
  - cd bin && ./xlnt.test
  - find .
