language: cpp
script:
  - mkdir build && cd build && cmake -G "Unix Makefiles" -D SHARED=0 -D AUTORUN_TESTS=1 -D BUILD_TESTS=1 ../cmake && make
compiler:
  - clang
  - gcc
install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
    - clang
notifications:
  email: false
sudo: false


