language: cpp
sudo: false
dist: trusty

notifications:
  email: false

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6 zlib1g libcrypto++9 libcrypto++9-dbg libcrypto++-dev cxxtest lcov
      env:
        - COVERAGE=ON
        - STATIC=ON
        - SAMPLES=OFF
        - BENCHMARKS=OFF

install:
 - export CC=gcc-6
 - export CXX=g++-6
 - gem install coveralls-lcov

script:
 - mkdir build
 - cd build
 - cmake -D STATIC=$STATIC -D BENCHMARKS=$BENCHMARKS -D SAMPLES=$SAMPLES -D COVERAGE=$COVERAGE -D CMAKE_BUILD_TYPE=Debug ..
 - make VERBOSE=1
 - ./tests/xlnt.test

after_success:
 - find .. -name "*.gcda"
 - lcov --compat-libtool --directory source/CMakeFiles/xlnt.dir --capture --output-file coverage.info --gcov-tool /usr/bin/gcov-6
 - coveralls-lcov coverage.info
