language: C++
compiler:
- clang
- gcc
script:
- mkdir build/cmake/build && cd build/cmake/build && cmake .. && make && cd ../../../bin && xlnt.test
install: ./tfussell/xlnt/build/install-dependencies.sh

