# from: https://github.com/nlohmann/json/blob/master/.travis.yml

language: cpp

sudo: false

matrix:
  include:
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-4.9', 'valgrind', 'python-pip', 'python-yaml']
      before_script:
        - pip install --user git+git://github.com/eddyxu/cpp-coveralls.git
      env: COMPILER=g++-4.9

    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-5', 'valgrind']
      env: COMPILER=g++-5

    - os: linux
      compiler: clang
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-precise-3.6']
          packages: ['clang-3.6', 'valgrind']
      env: COMPILER=clang++-3.6

script:
  - env
  - mkdir build
  - cd build
  - cmake -G "Unix Makefiles" -D SHARED=1 -D BUILD_TESTS=1 -D CMAKE_CXX_COMPILER=$COMPILER -D CMAKE_CXX_FLAGS="-lstdc++" ../cmake
  - make
  - ../bin/xlnt.test

after_success:
  - if [ "$COMPILER" = "g++-4.9" ]; then cd .. && mkdir build && cd build ; fi
  - if [ "$COMPILER" = "g++-4.9" ]; then cmake -G "Unix Makefiles" -D SHARED=1 -D BUILD_TESTS=1 -D CMAKE_CXX_COMPILER=$COMPILER -D CMAKE_CXX_FLAGS="-fprofile-arcs -ftest-coverage -lstdc++" ../cmake
  - if [ "$COMPILER" = "g++-4.9" ]; then make ; fi
  - if [ "$COMPILER" = "g++-4.9" ]; then ../bin/xlnt.test ; fi
  - if [ "$COMPILER" = "g++-4.9" ]; then coveralls --include ../source/worksheet/test_worksheet.hpp --gcov-options '\-lp' --gcov 'gcov-4.9' ; fi

notifications:
  email: false


