# from: https://github.com/nlohmann/json/blob/master/.travis.yml

language: cpp

sudo: required
dist: trusty

notifications:
  email: false

matrix:
  include:
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6 zlib1g libcrypto++9 libcrypto++9-dbg libcrypto++-dev cxxtest lcov ruby
      env:
        - COMPILER=g++-6
        - COVERAGE=ON
        - STATIC=ON
        - SAMPLES=ON
        - BENCHMARKS=ON

install:
 - gem install coveralls-lcov

before_script:
 - mkdir build
 - cmake -H . -B build -D STATIC=$STATIC -D BENCHMARKS=$BENCHMARKS -D SAMPLES=$SAMPLES -D COVERAGE=$COVERAGE -D CMAKE_CXX_COMPILER=$COMPILER -D CMAKE_BUILD_TYPE=Debug ..

script:
 - cmake --build build
 - ./build/tests/xlnt.test

after_success:
 - lcov --compat-libtool --directory build --capture --output-file coverage.info
 - coveralls-lcov coverage.info
