version: '{build}'
os: Visual Studio 2015

configuration:
- Debug

environment:
  matrix:
  - SHARED: ON
    STATIC: OFF
  - SHARED: OFF
    STATIC: ON

init: []
install: []
before_build:
- git submodule update --init --recursive
- cmake -H. -Bbuild -G "Visual Studio 14 2015 Win64" -D SHARED=%SHARED% -D STATIC=%STATIC% -D TESTS=1

build:
  project: build\xlnt.sln
  parallel: true
  verbosity: minimal

test_script:
- bin\xlnt.test.exe
